links_1 = [
    "www.samacare.com",
    "www.semantichealth.ai",
    "www.silnahealth.com",
    "www.streamlinehealth.net",
    "www.suki.ai",
    "www.synaptechealth.com",
    "www.synthpop.ai",
    "www.tailormed.co",
    "www.taxoconsulting.com",
    "www.tennr.com",
    "www.thoughtful.ai",
    "www.uipath.com",
    "www.valer.com",
    "www.willowhealthcare.com",
    "www.xpertdox.com",
    "www.marianaombu.com.ar",
    "www.mdclarity.com",
    "www.med-metrix.com",
    "www.nabla.com",
    "www.navina.ai",
    "www.notablehealth.com",
    "www.payzen.com",
    "www.pymedix.com",
    "www.penguinsolutions.com",
    "www.phare.health",
    "www.premierinc.com",
    "www.protegogroup.com",
    "www.regard.com",
    "www.risa.io",
    "www.rivethealth.com",
    "www.rotera.ai",
    "www.enjoincdi.com",
    "www.ethermed.ai",
    "www.etyon.com",
    "www.evidently.com",
    "www.flywire.com",
    "www.genhealth.ai",
    "www.theguardian.com",
    "www.humatahealth.com",
    "www.hyro.ai",
    "www.infinitus.ai",
    "www.infinx.com",
    "www.innovaccer.com",
    "www.knack.com",
    "www.knowtek.fi",
    "www.lumahealth.io",
    "www.getmagical.com",
    "www.joincandidhealth.com",
    "www.cedar.com",
    "www.claimable.com",
    "www.closedloop.ai",
    "www.codametrix.com",
    "www.cofactorai.com",
    "www.commure.com",
    "www.corrohealth.com",
    "www.crosbyhealth.com",
    "www.curationhealth.co",
    "www.daffodilsw.com",
    "www.decodahealth.com",
    "www.develophealth.io",
    "www.dteltelecom.com.br",
    "www.ectonenterprise.com",
    "www.elementfive.co",
    "www.adonis.io",
    "www.alaffiahealth.com",
    "www.ambiancehealthcare.com",
    "www.anomaly.com",
    "www.anteriorxl.com.au",
    "www.arintra.com",
    "www.arrow.com",
    "www.ascertain.com",
    "www.assort.com",
    "www.autonomize.ai",
    "www.banjohealth.com",
    "www.basys.com",
    "www.blueprism.com",
    "www.bookendsct.com",
    "www.brellium.com",
    "www.airhealth.com",
]


used = [
    # "www.abridge.com",
    # "www.accuitycpas.com",
    # "www.aihealth.ai",
    # "www.awellhealth.com",
    # "www.careviso.com",
    # "www.datavant.com",
    # "www.encoreglobal.com",
    # "www.experian.com",
    # "www.fathom.net",
    # "www.foreseemed.com",
    # "www.iodinesoftware.com",
    # "www.maverick-med.com",
    # "www.mdaudit.com",
    # "www.medicodio.com",
    # "www.nanonets.com",
    # "www.plenful.com",
    # "www.sifthealthcare.com",
    # "www.soharhealth.com",
    # "www.solventum.com",
    # "sparkchange.health",
]
